# Generated by Django 4.2.6 on 2023-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticida', models.CharField(max_length=255, verbose_name='pesticida')),
                ('planta', models.CharField(max_length=255, verbose_name='planta')),
                ('plaga', models.CharField(max_length=255, verbose_name='plaga')),
                ('nombre_cientifico', models.CharField(max_length=255, verbose_name='cientifico')),
                ('dosis', models.CharField(max_length=255, verbose_name='dosis')),
                ('informacion', models.CharField(max_length=2000, verbose_name='info')),
                ('etiqueta', models.CharField(max_length=2000, verbose_name='etiqueta')),
            ],
        ),
    ]
